# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba35ff532759684be4514717db1fa214"
name = "Case Studies"
handle = "case-studies-2"
application_url = "https://case-studies-brown.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_content,write_content,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://case-studies-brown.vercel.app/auth/callback",
  "https://case-studies-brown.vercel.app/auth/shopify/callback",
  "https://case-studies-brown.vercel.app/api/auth/callback"
]

[pos]
embedded = false
